import Constructable from '../Constructable';
import InternalHandler from '../InternalHandler';
import { INode, IDocumentOrShadowRoot, IGlobalEventHandlers, INonElementParentNode, IParentNode, IDocumentEventMap, IAddEventListenerOptions, IEventListenerOptions, IDOMImplementation, IDocumentType, IElement, ILocation, IDocumentReadyState, IHTMLElement, IHTMLHeadElement, IHTMLCollection, IHTMLScriptElement, IWindowProxy, IVisibilityState, IElementCreationOptions, IDocumentFragment, IText, ICDATASection, IComment, IProcessingInstruction, IAttr, IEvent, IRange, INodeIterator, ITreeWalker, INodeList, IDocument, ISelection } from '../interfaces';
import { INodeProperties, INodeReadonlyProperties } from './Node';
import { IDocumentOrShadowRootProperties, IDocumentOrShadowRootReadonlyProperties } from '../mixins/DocumentOrShadowRoot';
import { IGlobalEventHandlersProperties, IGlobalEventHandlersReadonlyProperties } from '../mixins/GlobalEventHandlers';
import { INonElementParentNodeProperties, INonElementParentNodeReadonlyProperties } from '../mixins/NonElementParentNode';
import { IParentNodeProperties, IParentNodeReadonlyProperties } from '../mixins/ParentNode';
export declare const getState: (instance: IDocument) => any, setState: <P = IDocumentProperties>(instance: IDocument, properties: P) => void, setHiddenState: <IHiddenProperties extends {}>(instance: IDocument, properties: IHiddenProperties) => void, setReadonlyOfDocument: (instance: IDocument, properties: IDocumentReadonlyProperties) => void;
export declare const internalHandler: InternalHandler<IDocument>;
export declare function DocumentGenerator(Node: Constructable<INode>, DocumentOrShadowRoot: Constructable<IDocumentOrShadowRoot>, GlobalEventHandlers: Constructable<IGlobalEventHandlers>, NonElementParentNode: Constructable<INonElementParentNode>, ParentNode: Constructable<IParentNode>): {
    new (): {
        readonly URL: string;
        readonly anchors: IHTMLCollection<IElement>;
        readonly applets: IHTMLCollection<IElement>;
        body: IHTMLElement | null;
        readonly characterSet: string;
        readonly charset: string;
        readonly compatMode: string;
        readonly contentType: string;
        cookie: string;
        readonly currentScript: IHTMLScriptElement | null;
        readonly defaultView: void | null;
        dir: string;
        readonly doctype: IDocumentType | null;
        readonly documentElement: IElement | null;
        readonly documentURI: string;
        readonly embeds: IHTMLCollection<IElement>;
        readonly forms: IHTMLCollection<IElement>;
        readonly head: IHTMLHeadElement | null;
        readonly hidden: boolean;
        readonly images: IHTMLCollection<IElement>;
        readonly implementation: IDOMImplementation;
        readonly inputEncoding: string;
        readonly lastModified: string;
        readonly links: IHTMLCollection<IElement>;
        readonly location: ILocation | null;
        onreadystatechange: ((this: IDocument, ev: IEvent) => any) | null;
        onvisibilitychange: ((this: IDocument, ev: IEvent) => any) | null;
        readonly plugins: IHTMLCollection<IElement>;
        readonly readyState: IDocumentReadyState;
        readonly referrer: string;
        readonly scripts: IHTMLCollection<IElement>;
        title: string;
        readonly visibilityState: IVisibilityState;
        adoptNode(node: INode): INode;
        captureEvents(): void;
        clear(): void;
        close(): void;
        createAttribute(localName: string): IAttr;
        createAttributeNS(namespace: string | null, qualifiedName: string): IAttr;
        createCDATASection(data: string): ICDATASection;
        createComment(data: string): IComment;
        createDocumentFragment(): IDocumentFragment;
        createElement(localName: string, options?: IElementCreationOptions | undefined): IElement;
        createElementNS(namespace: string | null, qualifiedName: string, options?: IElementCreationOptions | undefined): IElement;
        createEvent(eventInterface: string): IEvent;
        createNodeIterator(root: INode, whatToShow?: number | undefined, filter?: {
            acceptNode(node: INode): number;
        } | ((node: INode) => number) | null | undefined): INodeIterator;
        createProcessingInstruction(target: string, data: string): IProcessingInstruction;
        createRange(): IRange;
        createTextNode(data: string): IText;
        createTreeWalker(root: INode, whatToShow?: number | undefined, filter?: {
            acceptNode(node: INode): number;
        } | ((node: INode) => number) | null | undefined): ITreeWalker;
        getElementsByClassName(classNames: string): IHTMLCollection<IElement>;
        getElementsByName(elementName: string): INodeList<INode>;
        getElementsByTagName(qualifiedName: string): IHTMLCollection<IElement>;
        getElementsByTagNameNS(namespace: string | null, localName: string): IHTMLCollection<IElement>;
        getSelection(): ISelection | null;
        hasFocus(): boolean;
        importNode(node: INode, deep?: boolean | undefined): INode;
        open(type?: string | undefined, replace?: string | undefined): IDocument;
        releaseEvents(): void;
        write(...text: string[]): void;
        writeln(...text: string[]): void;
        addEventListener<K extends "change" | "readystatechange" | "visibilitychange" | "abort" | "auxclick" | "blur" | "cancel" | "canplay" | "canplaythrough" | "click" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "error" | "focus" | "input" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadend" | "loadstart" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "progress" | "ratechange" | "reset" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "select" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "volumechange" | "waiting" | "wheel">(type: K, listener: (this: IDocument, ev: IDocumentEventMap[K]) => any, options?: boolean | IAddEventListenerOptions | undefined): void;
        removeEventListener<K_1 extends "change" | "readystatechange" | "visibilitychange" | "abort" | "auxclick" | "blur" | "cancel" | "canplay" | "canplaythrough" | "click" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "error" | "focus" | "input" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadend" | "loadstart" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "progress" | "ratechange" | "reset" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "select" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "volumechange" | "waiting" | "wheel">(type: K_1, listener: (this: IDocument, ev: IDocumentEventMap[K_1]) => any, options?: boolean | IEventListenerOptions | undefined): void;
        readonly ATTRIBUTE_NODE: number;
        readonly CDATA_SECTION_NODE: number;
        readonly COMMENT_NODE: number;
        readonly DOCUMENT_FRAGMENT_NODE: number;
        readonly DOCUMENT_NODE: number;
        readonly DOCUMENT_POSITION_CONTAINED_BY: number;
        readonly DOCUMENT_POSITION_CONTAINS: number;
        readonly DOCUMENT_POSITION_DISCONNECTED: number;
        readonly DOCUMENT_POSITION_FOLLOWING: number;
        readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: number;
        readonly DOCUMENT_POSITION_PRECEDING: number;
        readonly DOCUMENT_TYPE_NODE: number;
        readonly ELEMENT_NODE: number;
        readonly ENTITY_NODE: number;
        readonly ENTITY_REFERENCE_NODE: number;
        readonly NOTATION_NODE: number;
        readonly PROCESSING_INSTRUCTION_NODE: number;
        readonly TEXT_NODE: number;
        readonly baseURI: string;
        readonly childNodes: INodeList<INode>;
        readonly firstChild: INode | null;
        readonly isConnected: boolean;
        readonly lastChild: INode | null;
        readonly nextSibling: INode | null;
        readonly nodeName: string;
        readonly nodeType: number;
        nodeValue: string | null;
        readonly ownerDocument: IDocument | null;
        readonly parentElement: IElement | null;
        readonly parentNode: INode | null;
        readonly previousSibling: INode | null;
        textContent: string | null;
        appendChild(node: INode): INode;
        cloneNode(deep?: boolean | undefined): INode;
        compareDocumentPosition(other: INode): number;
        contains(other: INode | null): boolean;
        getRootNode(options?: import("../interfaces").IGetRootNodeOptions | undefined): INode;
        hasChildNodes(): boolean;
        insertBefore(node: INode, child: INode | null): INode;
        isDefaultNamespace(namespace: string | null): boolean;
        isEqualNode(otherNode: INode | null): boolean;
        isSameNode(otherNode: INode | null): boolean;
        lookupNamespaceURI(prefix: string | null): string | null;
        lookupPrefix(namespace: string | null): string | null;
        normalize(): void;
        removeChild(child: INode): INode;
        replaceChild(node: INode, child: INode): INode;
        dispatchEvent(event: IEvent): boolean;
        readonly activeElement: IElement | null;
        onabort: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onauxclick: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onblur: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oncancel: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oncanplay: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oncanplaythrough: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onchange: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onclick: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onclose: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oncontextmenu: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oncuechange: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondblclick: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondrag: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragend: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragenter: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragexit: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragleave: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragover: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondragstart: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondrop: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ondurationchange: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onemptied: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onended: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onerror: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onfocus: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oninput: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        oninvalid: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onkeydown: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onkeypress: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onkeyup: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onload: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onloadeddata: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onloadedmetadata: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onloadend: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onloadstart: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmousedown: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmouseenter: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmouseleave: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmousemove: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmouseout: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmouseover: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onmouseup: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onpause: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onplay: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onplaying: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onprogress: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onratechange: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onreset: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onresize: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onscroll: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onsecuritypolicyviolation: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onseeked: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onseeking: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onselect: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onstalled: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onsubmit: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onsuspend: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ontimeupdate: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        ontoggle: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onvolumechange: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onwaiting: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        onwheel: ((this: IGlobalEventHandlers, ev: IEvent) => any) | null;
        getElementById(elementId: string): IElement | null;
        readonly childElementCount: number;
        readonly children: IHTMLCollection<IElement>;
        readonly firstElementChild: IElement | null;
        readonly lastElementChild: IElement | null;
        append(...nodes: (string | INode)[]): void;
        prepend(...nodes: (string | INode)[]): void;
        querySelector(selectors: string): IElement | null;
        querySelectorAll(selectors: string): INodeList<INode>;
    };
};
export interface IDocumentProperties extends INodeProperties, IDocumentOrShadowRootProperties, IGlobalEventHandlersProperties, INonElementParentNodeProperties, IParentNodeProperties {
    URL?: string;
    anchors?: IHTMLCollection;
    applets?: IHTMLCollection;
    body?: IHTMLElement | null;
    characterSet?: string;
    charset?: string;
    compatMode?: string;
    contentType?: string;
    cookie?: string;
    currentScript?: IHTMLScriptElement | null;
    defaultView?: IWindowProxy | null;
    dir?: string;
    doctype?: IDocumentType | null;
    documentElement?: IElement | null;
    documentURI?: string;
    embeds?: IHTMLCollection;
    forms?: IHTMLCollection;
    head?: IHTMLHeadElement | null;
    hidden?: boolean;
    images?: IHTMLCollection;
    implementation?: IDOMImplementation;
    inputEncoding?: string;
    lastModified?: string;
    links?: IHTMLCollection;
    location?: ILocation | null;
    onreadystatechange?: ((this: IDocument, ev: IEvent) => any) | null;
    onvisibilitychange?: ((this: IDocument, ev: IEvent) => any) | null;
    plugins?: IHTMLCollection;
    readyState?: IDocumentReadyState;
    referrer?: string;
    scripts?: IHTMLCollection;
    title?: string;
    visibilityState?: IVisibilityState;
}
export interface IDocumentReadonlyProperties extends INodeReadonlyProperties, IDocumentOrShadowRootReadonlyProperties, IGlobalEventHandlersReadonlyProperties, INonElementParentNodeReadonlyProperties, IParentNodeReadonlyProperties {
    URL?: string;
    anchors?: IHTMLCollection;
    applets?: IHTMLCollection;
    characterSet?: string;
    charset?: string;
    compatMode?: string;
    contentType?: string;
    currentScript?: IHTMLScriptElement | null;
    defaultView?: IWindowProxy | null;
    doctype?: IDocumentType | null;
    documentElement?: IElement | null;
    documentURI?: string;
    embeds?: IHTMLCollection;
    forms?: IHTMLCollection;
    head?: IHTMLHeadElement | null;
    hidden?: boolean;
    images?: IHTMLCollection;
    implementation?: IDOMImplementation;
    inputEncoding?: string;
    lastModified?: string;
    links?: IHTMLCollection;
    location?: ILocation | null;
    plugins?: IHTMLCollection;
    readyState?: IDocumentReadyState;
    referrer?: string;
    scripts?: IHTMLCollection;
    visibilityState?: IVisibilityState;
}
export declare const DocumentPropertyKeys: string[];
export declare const DocumentConstantKeys: string[];
